/**
 * Command Registry — Single source of truth for all bot commands.
 *
 * Used by:
 * - In-bot /help system (runtime)
 * - VitePress documentation site (build-time generation)
 *
 * Keep this file free of grammY or runtime imports so it can be
 * safely imported by the doc generation script.
 */

export type PermissionLevel =
  | "everyone"
  | "admin"
  | "creator"
  | "owner"
  | "pm-only"
  | "fed-owner"
  | "fed-admin"
  | "bot-wallet";

export type CommandCategory =
  | "core"
  | "moderation"
  | "anti-spam"
  | "greetings"
  | "content"
  | "federations"
  | "zenon"
  | "settings";

export interface CommandEntry {
  /** Command name without slash, e.g. "ban" */
  name: string;
  category: CommandCategory;
  permission: PermissionLevel;
  /** One-sentence description for category listings */
  description: string;
  /** Detailed description for per-command help view */
  longDescription?: string;
  /** Usage syntax, e.g. "/ban <user> [reason]" */
  usage: string;
  /** Example invocations */
  examples: string[];
  /** Caveats, tips, related commands */
  notes?: string[];
  /** Source module name */
  module: string;
}

export const CATEGORIES: Record<
  CommandCategory,
  { label: string; description: string; icon: string }
> = {
  core: {
    label: "Core",
    description: "Basic bot interaction and help",
    icon: "🤖",
  },
  moderation: {
    label: "Moderation",
    description: "Ban, mute, kick, warn, and admin management",
    icon: "🔨",
  },
  "anti-spam": {
    label: "Anti-Spam",
    description: "CAPTCHA, locks, blocklist, flood and raid protection",
    icon: "🛡",
  },
  greetings: {
    label: "Greetings",
    description: "Welcome and goodbye messages",
    icon: "👋",
  },
  content: {
    label: "Content",
    description: "Notes, filters, rules, pins, and auto-cleaning",
    icon: "📋",
  },
  federations: {
    label: "Federations",
    description: "Cross-group ban federation system",
    icon: "🌐",
  },
  zenon: {
    label: "Zenon Network",
    description: "Blockchain wallet, staking, pillars, and token gating",
    icon: "⛓",
  },
  settings: {
    label: "Settings",
    description: "Logging, connections, cleaning, and command toggling",
    icon: "⚙️",
  },
};

export const COMMAND_REGISTRY: CommandEntry[] = [
  // ─── Core ───────────────────────────────────────────────
  {
    name: "start",
    category: "core",
    permission: "everyone",
    description: "Start the bot and see the intro message.",
    usage: "/start",
    examples: ["/start"],
    module: "start",
  },
  {
    name: "help",
    category: "core",
    permission: "everyone",
    description: "Browse all available commands by category.",
    longDescription:
      "In PM, shows an interactive command browser with category buttons. In groups, sends a link to open help in PM. Use /help <command> to look up a specific command.",
    usage: "/help [command]",
    examples: ["/help", "/help ban", "/help captcha"],
    module: "start",
  },

  // ─── Moderation: Bans ──────────────────────────────────
  {
    name: "ban",
    category: "moderation",
    permission: "admin",
    description: "Permanently ban a user from the group.",
    longDescription:
      "Bans a user so they cannot rejoin unless unbanned. Target by replying to their message, @username, or user ID. An optional reason is logged.",
    usage: "/ban <user> [reason]",
    examples: [
      "Reply to a message: /ban",
      "/ban @username spamming",
      "/ban 123456789 posting malware",
    ],
    notes: ["See also: /tban, /dban, /sban"],
    module: "bans",
  },
  {
    name: "tban",
    category: "moderation",
    permission: "admin",
    description: "Temporarily ban a user for a specified duration.",
    usage: "/tban <user> <duration> [reason]",
    examples: [
      "/tban @username 1d",
      "/tban @username 2h posting nsfw",
      "Reply: /tban 30m",
    ],
    notes: ["Duration format: 30m, 2h, 7d, 1w"],
    module: "bans",
  },
  {
    name: "dban",
    category: "moderation",
    permission: "admin",
    description: "Delete the replied-to message and ban the sender.",
    usage: "/dban [reason]",
    examples: ["Reply to a message: /dban spam"],
    notes: ["Must be used as a reply"],
    module: "bans",
  },
  {
    name: "sban",
    category: "moderation",
    permission: "admin",
    description: "Silently ban a user with no confirmation message.",
    usage: "/sban <user> [duration] [reason]",
    examples: ["Reply: /sban", "/sban @username 1d"],
    notes: ["Deletes the command message; no reply is sent"],
    module: "bans",
  },
  {
    name: "unban",
    category: "moderation",
    permission: "admin",
    description: "Remove a ban from a user.",
    usage: "/unban <user>",
    examples: ["/unban @username", "/unban 123456789"],
    module: "bans",
  },
  {
    name: "mute",
    category: "moderation",
    permission: "admin",
    description: "Permanently mute a user (revoke send permissions).",
    usage: "/mute <user> [reason]",
    examples: ["Reply: /mute", "/mute @username off-topic"],
    notes: ["See also: /tmute, /dmute, /smute"],
    module: "bans",
  },
  {
    name: "tmute",
    category: "moderation",
    permission: "admin",
    description: "Temporarily mute a user for a specified duration.",
    usage: "/tmute <user> <duration> [reason]",
    examples: ["/tmute @username 1h", "Reply: /tmute 30m"],
    notes: ["Duration format: 30m, 2h, 7d, 1w"],
    module: "bans",
  },
  {
    name: "dmute",
    category: "moderation",
    permission: "admin",
    description: "Delete the replied-to message and mute the sender.",
    usage: "/dmute [reason]",
    examples: ["Reply: /dmute spamming stickers"],
    notes: ["Must be used as a reply"],
    module: "bans",
  },
  {
    name: "smute",
    category: "moderation",
    permission: "admin",
    description: "Silently mute a user with no confirmation message.",
    usage: "/smute <user> [duration] [reason]",
    examples: ["Reply: /smute", "/smute @username 2h"],
    notes: ["Deletes the command message; no reply is sent"],
    module: "bans",
  },
  {
    name: "unmute",
    category: "moderation",
    permission: "admin",
    description: "Remove a mute from a user.",
    usage: "/unmute <user>",
    examples: ["/unmute @username", "Reply: /unmute"],
    module: "bans",
  },
  {
    name: "kick",
    category: "moderation",
    permission: "admin",
    description: "Kick a user from the group (they can rejoin).",
    longDescription:
      "Kicks a user by banning and immediately unbanning them. Unlike /ban, the user can rejoin via invite link.",
    usage: "/kick <user> [reason]",
    examples: ["Reply: /kick", "/kick @username being disruptive"],
    notes: ["See also: /dkick, /skick"],
    module: "bans",
  },
  {
    name: "dkick",
    category: "moderation",
    permission: "admin",
    description: "Delete the replied-to message and kick the sender.",
    usage: "/dkick [reason]",
    examples: ["Reply: /dkick"],
    notes: ["Must be used as a reply"],
    module: "bans",
  },
  {
    name: "skick",
    category: "moderation",
    permission: "admin",
    description: "Silently kick a user with no confirmation message.",
    usage: "/skick <user>",
    examples: ["Reply: /skick"],
    notes: ["Deletes the command message; no reply is sent"],
    module: "bans",
  },

  // ─── Moderation: Warnings ──────────────────────────────
  {
    name: "warn",
    category: "moderation",
    permission: "admin",
    description: "Issue a warning to a user.",
    longDescription:
      "Warns a user and tracks the count. When the warn limit is reached, the configured action (ban/mute/kick) is automatically applied.",
    usage: "/warn <user> [reason]",
    examples: ["Reply: /warn stop spamming", "/warn @username rule violation"],
    notes: ["See also: /dwarn, /swarn"],
    module: "warnings",
  },
  {
    name: "dwarn",
    category: "moderation",
    permission: "admin",
    description: "Delete the replied-to message and warn the sender.",
    usage: "/dwarn [reason]",
    examples: ["Reply: /dwarn inappropriate content"],
    notes: ["Must be used as a reply"],
    module: "warnings",
  },
  {
    name: "swarn",
    category: "moderation",
    permission: "admin",
    description: "Silently warn a user with no confirmation message.",
    usage: "/swarn <user> [reason]",
    examples: ["Reply: /swarn"],
    notes: ["Deletes both the target and command messages"],
    module: "warnings",
  },
  {
    name: "rmwarn",
    category: "moderation",
    permission: "admin",
    description: "Remove the most recent warning from a user.",
    usage: "/rmwarn <user>",
    examples: ["Reply: /rmwarn", "/rmwarn @username"],
    module: "warnings",
  },
  {
    name: "resetwarn",
    category: "moderation",
    permission: "admin",
    description: "Clear all warnings for a user.",
    usage: "/resetwarn <user>",
    examples: ["/resetwarn @username", "Reply: /resetwarn"],
    module: "warnings",
  },
  {
    name: "warns",
    category: "moderation",
    permission: "everyone",
    description: "View a user's current warnings.",
    usage: "/warns [user]",
    examples: ["/warns", "/warns @username", "Reply: /warns"],
    module: "warnings",
  },
  {
    name: "warnings",
    category: "moderation",
    permission: "everyone",
    description: "Show the chat's warning configuration.",
    usage: "/warnings",
    examples: ["/warnings"],
    notes: ["Shows warn limit, action mode, and expiry time"],
    module: "warnings",
  },
  {
    name: "setwarnlimit",
    category: "moderation",
    permission: "admin",
    description: "Set the maximum number of warnings before action.",
    usage: "/setwarnlimit <1-999>",
    examples: ["/setwarnlimit 3", "/setwarnlimit 5"],
    module: "warnings",
  },
  {
    name: "setwarnmode",
    category: "moderation",
    permission: "admin",
    description: "Set the action taken when the warn limit is reached.",
    usage: "/setwarnmode <ban|mute|kick|tban|tmute>",
    examples: ["/setwarnmode ban", "/setwarnmode tmute"],
    module: "warnings",
  },
  {
    name: "setwarntime",
    category: "moderation",
    permission: "admin",
    description: "Set how long warnings last before expiring.",
    usage: "/setwarntime <duration|off>",
    examples: ["/setwarntime 7d", "/setwarntime off"],
    notes: ["Use 'off' to make warnings permanent"],
    module: "warnings",
  },

  // ─── Moderation: Admin Management ──────────────────────
  {
    name: "promote",
    category: "moderation",
    permission: "admin",
    description: "Promote a user to admin.",
    usage: "/promote <user>",
    examples: ["/promote @username", "Reply: /promote"],
    module: "admin",
  },
  {
    name: "demote",
    category: "moderation",
    permission: "admin",
    description: "Demote an admin back to regular member.",
    usage: "/demote <user>",
    examples: ["/demote @username", "Reply: /demote"],
    module: "admin",
  },
  {
    name: "adminlist",
    category: "moderation",
    permission: "everyone",
    description: "List all administrators in the chat.",
    usage: "/adminlist",
    examples: ["/adminlist"],
    module: "admin",
  },
  {
    name: "adminerror",
    category: "settings",
    permission: "admin",
    description: "Toggle error messages when non-admins use admin commands.",
    usage: "/adminerror <on|off>",
    examples: ["/adminerror on", "/adminerror off"],
    module: "admin",
  },
  {
    name: "anonadmin",
    category: "settings",
    permission: "creator",
    description: "Toggle trusting anonymous admins with full permissions.",
    usage: "/anonadmin <on|off>",
    examples: ["/anonadmin on"],
    notes: ["Creator only. Security risk when enabled."],
    module: "admin",
  },
  {
    name: "admincache",
    category: "settings",
    permission: "admin",
    description: "Force-refresh the admin list cache.",
    usage: "/admincache",
    examples: ["/admincache"],
    module: "admin",
  },

  // ─── Moderation: Reports ───────────────────────────────
  {
    name: "reports",
    category: "settings",
    permission: "admin",
    description: "Toggle the reporting feature.",
    usage: "/reports <on|off>",
    examples: ["/reports on", "/reports off"],
    module: "reports",
  },
  {
    name: "report",
    category: "moderation",
    permission: "everyone",
    description: "Report a message to all group admins.",
    longDescription:
      "Reply to a message to report it. All admins receive a notification in PM. Only non-admins can use this command. You can also mention @admin to trigger a report.",
    usage: "/report",
    examples: ["Reply to a message: /report"],
    notes: ["Admins cannot report. @admin mention also works."],
    module: "reports",
  },

  // ─── Moderation: Purges ────────────────────────────────
  {
    name: "del",
    category: "moderation",
    permission: "admin",
    description: "Delete a single replied-to message.",
    usage: "/del",
    examples: ["Reply to a message: /del"],
    module: "purges",
  },
  {
    name: "purge",
    category: "moderation",
    permission: "admin",
    description: "Bulk-delete messages from the replied-to message to now.",
    longDescription:
      "Deletes all messages in the range from the replied-to message up to the command. An optional count limits how many messages to delete. Hard cap of 200 messages.",
    usage: "/purge [count]",
    examples: ["Reply to a message: /purge", "Reply: /purge 50"],
    notes: ["Max 200 messages per purge"],
    module: "purges",
  },
  {
    name: "spurge",
    category: "moderation",
    permission: "admin",
    description: "Silent purge — bulk-delete with no confirmation.",
    usage: "/spurge [count]",
    examples: ["Reply: /spurge", "Reply: /spurge 30"],
    notes: ["Same as /purge but no confirmation message"],
    module: "purges",
  },
  {
    name: "purgefrom",
    category: "moderation",
    permission: "admin",
    description: "Mark the start of a range purge.",
    usage: "/purgefrom",
    examples: ["Reply to the oldest message: /purgefrom"],
    notes: ["Follow up with /purgeto to complete"],
    module: "purges",
  },
  {
    name: "purgeto",
    category: "moderation",
    permission: "admin",
    description: "Complete a range purge started with /purgefrom.",
    usage: "/purgeto",
    examples: ["Reply to the newest message: /purgeto"],
    notes: ["Must use /purgefrom first"],
    module: "purges",
  },

  // ─── Moderation: Approvals ─────────────────────────────
  {
    name: "approve",
    category: "moderation",
    permission: "admin",
    description: "Approve a user (exempt from automated moderation).",
    longDescription:
      "Approved users bypass antiflood, filters, blocklists, and locks. Useful for trusted users or bots.",
    usage: "/approve <user> [reason]",
    examples: ["/approve @username trusted member", "Reply: /approve"],
    module: "approvals",
  },
  {
    name: "approval",
    category: "moderation",
    permission: "everyone",
    description: "Check if a user is approved.",
    usage: "/approval <user>",
    examples: ["/approval @username", "Reply: /approval"],
    module: "approvals",
  },
  {
    name: "approved",
    category: "moderation",
    permission: "everyone",
    description: "List all approved users in the chat.",
    usage: "/approved",
    examples: ["/approved"],
    module: "approvals",
  },
  {
    name: "unapprove",
    category: "moderation",
    permission: "admin",
    description: "Remove approved status from a user.",
    usage: "/unapprove <user>",
    examples: ["/unapprove @username", "Reply: /unapprove"],
    module: "approvals",
  },
  {
    name: "unapproveall",
    category: "moderation",
    permission: "creator",
    description: "Remove all approvals in the chat.",
    usage: "/unapproveall",
    examples: ["/unapproveall"],
    notes: ["Creator only"],
    module: "approvals",
  },

  // ─── Anti-Spam: Locks ──────────────────────────────────
  {
    name: "locks",
    category: "anti-spam",
    permission: "everyone",
    description: "Show active content locks.",
    usage: "/locks [list]",
    examples: ["/locks", "/locks list"],
    notes: ["Use 'list' to see all available lock types"],
    module: "locks",
  },
  {
    name: "locktypes",
    category: "anti-spam",
    permission: "everyone",
    description: "List all available lock type names.",
    usage: "/locktypes",
    examples: ["/locktypes"],
    module: "locks",
  },
  {
    name: "lock",
    category: "anti-spam",
    permission: "admin",
    description: "Lock one or more content types.",
    longDescription:
      "Locked content from non-admins is automatically deleted. You can lock multiple types at once. Supports optional reason (### reason) and mode override ({mode}).",
    usage: "/lock <type> [type2] [### reason] [{mode}]",
    examples: [
      "/lock sticker",
      "/lock url forward",
      "/lock gif ### no gifs allowed",
      "/lock photo {warn}",
    ],
    notes: ["See /locktypes for all available types"],
    module: "locks",
  },
  {
    name: "unlock",
    category: "anti-spam",
    permission: "admin",
    description: "Unlock one or more content types.",
    usage: "/unlock <type> [type2]",
    examples: ["/unlock sticker", "/unlock url forward"],
    module: "locks",
  },
  {
    name: "lockwarns",
    category: "anti-spam",
    permission: "admin",
    description: "Toggle warnings for lock violations.",
    usage: "/lockwarns <on|off>",
    examples: ["/lockwarns on", "/lockwarns off"],
    module: "locks",
  },
  {
    name: "allowlist",
    category: "anti-spam",
    permission: "admin",
    description: "View or add items to the lock allowlist.",
    usage: "/allowlist [item] [item2]",
    examples: ["/allowlist", "/allowlist example.com"],
    module: "locks",
  },
  {
    name: "rmallowlist",
    category: "anti-spam",
    permission: "admin",
    description: "Remove items from the lock allowlist.",
    usage: "/rmallowlist <item> [item2]",
    examples: ["/rmallowlist example.com"],
    module: "locks",
  },
  {
    name: "rmallowlistall",
    category: "anti-spam",
    permission: "creator",
    description: "Clear the entire lock allowlist.",
    usage: "/rmallowlistall",
    examples: ["/rmallowlistall"],
    notes: ["Creator only"],
    module: "locks",
  },

  // ─── Anti-Spam: CAPTCHA ────────────────────────────────
  {
    name: "captcha",
    category: "anti-spam",
    permission: "admin",
    description: "Enable or disable CAPTCHA verification for new members.",
    longDescription:
      "When enabled, new members are muted and must complete a challenge before they can send messages. Without arguments, shows the current settings.",
    usage: "/captcha [on|off]",
    examples: ["/captcha on", "/captcha off", "/captcha"],
    module: "captcha",
  },
  {
    name: "captchamode",
    category: "anti-spam",
    permission: "admin",
    description: "Set the CAPTCHA challenge type.",
    usage: "/captchamode <button|text|math|custom>",
    examples: ["/captchamode math", "/captchamode button"],
    notes: [
      "button: click to verify. text: type a code. math: solve addition. custom: custom button text.",
    ],
    module: "captcha",
  },
  {
    name: "setcaptchatext",
    category: "anti-spam",
    permission: "admin",
    description: "Set custom text for the CAPTCHA verification button.",
    usage: "/setcaptchatext <text>",
    examples: ['/setcaptchatext Click here to verify'],
    module: "captcha",
  },
  {
    name: "resetcaptchatext",
    category: "anti-spam",
    permission: "admin",
    description: "Reset the CAPTCHA button text to default.",
    usage: "/resetcaptchatext",
    examples: ["/resetcaptchatext"],
    module: "captcha",
  },
  {
    name: "captchakick",
    category: "anti-spam",
    permission: "admin",
    description: "Toggle kicking users who fail to solve the CAPTCHA.",
    usage: "/captchakick <on|off>",
    examples: ["/captchakick on"],
    module: "captcha",
  },
  {
    name: "captchakicktime",
    category: "anti-spam",
    permission: "admin",
    description: "Set how long users have to solve the CAPTCHA before being kicked.",
    usage: "/captchakicktime <duration>",
    examples: ["/captchakicktime 5m", "/captchakicktime 1h"],
    notes: ["Range: 5 minutes to 1 day"],
    module: "captcha",
  },
  {
    name: "captcharules",
    category: "anti-spam",
    permission: "admin",
    description: "Require rules acceptance during CAPTCHA verification.",
    usage: "/captcharules <on|off>",
    examples: ["/captcharules on"],
    module: "captcha",
  },
  {
    name: "captchamutetime",
    category: "anti-spam",
    permission: "admin",
    description: "Set auto-unmute duration after CAPTCHA (or disable).",
    usage: "/captchamutetime <duration|off>",
    examples: ["/captchamutetime 10m", "/captchamutetime off"],
    module: "captcha",
  },

  // ─── Anti-Spam: Blocklist ──────────────────────────────
  {
    name: "blocklist",
    category: "anti-spam",
    permission: "everyone",
    description: "List all blocklist triggers for the chat.",
    usage: "/blocklist",
    examples: ["/blocklist"],
    module: "blocklist",
  },
  {
    name: "addblocklist",
    category: "anti-spam",
    permission: "admin",
    description: "Add one or more blocklist triggers.",
    longDescription:
      'Supports single words, "quoted phrases", batch (word1, "phrase 2"), type prefixes (exact:, prefix:, lookalike:, stickerpack:, file:, forward:, inline:, username:, name:), and per-trigger mode override ({ban}, {mute}, etc.).',
    usage: '/addblocklist <trigger> [reason] [{mode}]',
    examples: [
      "/addblocklist spam",
      '/addblocklist "buy followers" advertising {ban}',
      '/addblocklist (spam, "crypto scam", badword)',
      "/addblocklist lookalike:hello",
    ],
    notes: ["Max trigger length: 100 characters"],
    module: "blocklist",
  },
  {
    name: "rmblocklist",
    category: "anti-spam",
    permission: "admin",
    description: "Remove one or more blocklist triggers.",
    usage: "/rmblocklist <trigger> or (trigger1, trigger2)",
    examples: ["/rmblocklist spam", "/rmblocklist (spam, badword)"],
    module: "blocklist",
  },
  {
    name: "rmblocklistall",
    category: "anti-spam",
    permission: "creator",
    description: "Remove all blocklist triggers.",
    usage: "/rmblocklistall",
    examples: ["/rmblocklistall"],
    notes: ["Creator only"],
    module: "blocklist",
  },
  {
    name: "blocklistmode",
    category: "anti-spam",
    permission: "admin",
    description: "Set the default action for blocklist matches.",
    usage: "/blocklistmode <nothing|warn|kick|ban|mute|tban|tmute>",
    examples: ["/blocklistmode ban", "/blocklistmode warn"],
    module: "blocklist",
  },
  {
    name: "blocklistdelete",
    category: "anti-spam",
    permission: "admin",
    description: "Toggle deleting messages that match the blocklist.",
    usage: "/blocklistdelete <on|off>",
    examples: ["/blocklistdelete on"],
    module: "blocklist",
  },
  {
    name: "setblocklistreason",
    category: "anti-spam",
    permission: "admin",
    description: "Set a default reason for blocklist actions.",
    usage: "/setblocklistreason <reason>",
    examples: ["/setblocklistreason Matched blocklist trigger"],
    module: "blocklist",
  },
  {
    name: "resetblocklistreason",
    category: "anti-spam",
    permission: "admin",
    description: "Reset the blocklist reason to default.",
    usage: "/resetblocklistreason",
    examples: ["/resetblocklistreason"],
    module: "blocklist",
  },

  // ─── Anti-Spam: Antiflood ──────────────────────────────
  {
    name: "flood",
    category: "anti-spam",
    permission: "everyone",
    description: "Show current antiflood settings.",
    usage: "/flood",
    examples: ["/flood"],
    module: "antiflood",
  },
  {
    name: "setflood",
    category: "anti-spam",
    permission: "admin",
    description: "Set the flood message limit or disable.",
    usage: "/setflood <2-100|off>",
    examples: ["/setflood 10", "/setflood off"],
    module: "antiflood",
  },
  {
    name: "setfloodtimer",
    category: "anti-spam",
    permission: "admin",
    description: "Set the flood detection time window.",
    usage: "/setfloodtimer <duration>",
    examples: ["/setfloodtimer 5m", "/setfloodtimer 30s"],
    notes: ["Range: 5 seconds to 1 day"],
    module: "antiflood",
  },
  {
    name: "setfloodmode",
    category: "anti-spam",
    permission: "admin",
    description: "Set the action taken when a user floods.",
    usage: "/setfloodmode <ban|mute|kick|tban|tmute>",
    examples: ["/setfloodmode mute", "/setfloodmode tban"],
    module: "antiflood",
  },
  {
    name: "clearflood",
    category: "anti-spam",
    permission: "admin",
    description: "Toggle deleting all flood messages when triggered.",
    usage: "/clearflood <on|off>",
    examples: ["/clearflood on"],
    module: "antiflood",
  },

  // ─── Anti-Spam: Antiraid ───────────────────────────────
  {
    name: "antiraid",
    category: "anti-spam",
    permission: "admin",
    description: "Enable or disable antiraid mode.",
    longDescription:
      "When active, new members joining the group are immediately kicked. Without arguments, shows current settings including raid time and auto-detection threshold.",
    usage: "/antiraid [on|off]",
    examples: ["/antiraid on", "/antiraid off", "/antiraid"],
    module: "antiraid",
  },
  {
    name: "raidtime",
    category: "anti-spam",
    permission: "admin",
    description: "Set how long antiraid mode stays active.",
    usage: "/raidtime <duration>",
    examples: ["/raidtime 6h", "/raidtime 1d"],
    notes: ["Range: 5 minutes to 7 days"],
    module: "antiraid",
  },
  {
    name: "raidactiontime",
    category: "anti-spam",
    permission: "admin",
    description: "Set the action window duration for raid kicks.",
    usage: "/raidactiontime <duration>",
    examples: ["/raidactiontime 1h", "/raidactiontime 30m"],
    notes: ["Range: 1 minute to 1 day"],
    module: "antiraid",
  },
  {
    name: "autoantiraid",
    category: "anti-spam",
    permission: "admin",
    description: "Auto-enable raid mode when N users join within 1 minute.",
    usage: "/autoantiraid <2-100|off>",
    examples: ["/autoantiraid 10", "/autoantiraid off"],
    module: "antiraid",
  },

  // ─── Greetings ─────────────────────────────────────────
  {
    name: "welcome",
    category: "greetings",
    permission: "admin",
    description: "Toggle or view welcome message settings.",
    longDescription:
      "With on/off, enables or disables welcome messages. Without arguments, shows the current status and welcome message template.",
    usage: "/welcome [on|off]",
    examples: ["/welcome on", "/welcome off", "/welcome"],
    module: "greetings",
  },
  {
    name: "setwelcome",
    category: "greetings",
    permission: "admin",
    description: "Set a custom welcome message.",
    longDescription:
      "Supports template variables: {first}, {last}, {fullname}, {username}, {mention}, {id}, {chatname}. Supports inline buttons with [text](buttonurl://url) syntax. Reply to media to attach it.",
    usage: "/setwelcome <message>",
    examples: [
      "/setwelcome Welcome {mention} to {chatname}!",
      "/setwelcome Hey {first}! Read the /rules",
    ],
    notes: [
      "Fillings: {first}, {last}, {fullname}, {username}, {mention}, {id}, {chatname}",
    ],
    module: "greetings",
  },
  {
    name: "resetwelcome",
    category: "greetings",
    permission: "admin",
    description: "Reset the welcome message to default.",
    usage: "/resetwelcome",
    examples: ["/resetwelcome"],
    module: "greetings",
  },
  {
    name: "goodbye",
    category: "greetings",
    permission: "admin",
    description: "Toggle or view goodbye message settings.",
    usage: "/goodbye [on|off]",
    examples: ["/goodbye on", "/goodbye off", "/goodbye"],
    module: "greetings",
  },
  {
    name: "setgoodbye",
    category: "greetings",
    permission: "admin",
    description: "Set a custom goodbye message.",
    usage: "/setgoodbye <message>",
    examples: ["/setgoodbye Goodbye {first}, we'll miss you!"],
    notes: ["Same template variables as /setwelcome"],
    module: "greetings",
  },
  {
    name: "resetgoodbye",
    category: "greetings",
    permission: "admin",
    description: "Reset the goodbye message to default.",
    usage: "/resetgoodbye",
    examples: ["/resetgoodbye"],
    module: "greetings",
  },
  {
    name: "cleanwelcome",
    category: "greetings",
    permission: "admin",
    description: "Auto-delete the previous welcome when a new member joins.",
    usage: "/cleanwelcome <on|off>",
    examples: ["/cleanwelcome on"],
    module: "greetings",
  },

  // ─── Content: Rules ────────────────────────────────────
  {
    name: "rules",
    category: "content",
    permission: "everyone",
    description: "Display the group rules.",
    longDescription:
      "Shows the group rules inline or via a PM button (if private rules is enabled).",
    usage: "/rules",
    examples: ["/rules"],
    module: "rules",
  },
  {
    name: "setrules",
    category: "content",
    permission: "admin",
    description: "Set the group rules.",
    usage: "/setrules <rules text>",
    examples: ["/setrules 1. No spam\\n2. Be respectful"],
    module: "rules",
  },
  {
    name: "resetrules",
    category: "content",
    permission: "admin",
    description: "Clear the group rules.",
    usage: "/resetrules",
    examples: ["/resetrules"],
    module: "rules",
  },
  {
    name: "privaterules",
    category: "content",
    permission: "admin",
    description: "Toggle sending rules via PM button.",
    usage: "/privaterules <on|off>",
    examples: ["/privaterules on"],
    module: "rules",
  },
  {
    name: "setrulesbutton",
    category: "content",
    permission: "admin",
    description: "Add a custom button to the rules message.",
    usage: "/setrulesbutton <text>|<url>",
    examples: ["/setrulesbutton Full Rules|https://example.com/rules"],
    module: "rules",
  },
  {
    name: "resetrulesbutton",
    category: "content",
    permission: "admin",
    description: "Remove the custom rules button.",
    usage: "/resetrulesbutton",
    examples: ["/resetrulesbutton"],
    module: "rules",
  },

  // ─── Content: Notes ────────────────────────────────────
  {
    name: "save",
    category: "content",
    permission: "admin",
    description: "Save a note with optional media and buttons.",
    longDescription:
      "Saves content retrievable by name. Reply to media to attach it. Supports {private} and {admin} tags, template variables, and inline buttons.",
    usage: "/save <name> <content>",
    examples: [
      "/save welcome Welcome to the group!",
      "/save faq Check our FAQ: [Link](buttonurl://example.com)",
    ],
    module: "notes",
  },
  {
    name: "get",
    category: "content",
    permission: "everyone",
    description: "Retrieve a saved note.",
    usage: "/get <name>",
    examples: ["/get welcome", "/get faq"],
    notes: ["You can also use #notename as a shortcut"],
    module: "notes",
  },
  {
    name: "notes",
    category: "content",
    permission: "everyone",
    description: "List all saved notes in the group.",
    usage: "/notes",
    examples: ["/notes"],
    module: "notes",
  },
  {
    name: "clear",
    category: "content",
    permission: "admin",
    description: "Delete a saved note.",
    usage: "/clear <name>",
    examples: ["/clear welcome"],
    module: "notes",
  },
  {
    name: "privatenotes",
    category: "content",
    permission: "admin",
    description: "Toggle sending notes via PM.",
    usage: "/privatenotes <on|off>",
    examples: ["/privatenotes on"],
    module: "notes",
  },

  // ─── Content: Filters ──────────────────────────────────
  {
    name: "filter",
    category: "content",
    permission: "admin",
    description: "Add an auto-reply filter.",
    longDescription:
      'Triggers on incoming messages matching the keyword. Supports trigger type prefixes: prefix:, exact:, command:. Default is substring match. Use "quoted keyword" for multi-word triggers.',
    usage: '/filter <keyword> <response>',
    examples: [
      "/filter hello Hey there!",
      '/filter "how are you" I\'m doing great!',
      "/filter command:rules Check /rules",
    ],
    module: "filters",
  },
  {
    name: "stop",
    category: "content",
    permission: "admin",
    description: "Remove a filter.",
    usage: "/stop <keyword>",
    examples: ["/stop hello"],
    module: "filters",
  },
  {
    name: "stopall",
    category: "content",
    permission: "creator",
    description: "Remove all filters.",
    usage: "/stopall",
    examples: ["/stopall"],
    notes: ["Creator only"],
    module: "filters",
  },
  {
    name: "filters",
    category: "content",
    permission: "everyone",
    description: "List all active filters.",
    usage: "/filters",
    examples: ["/filters"],
    module: "filters",
  },

  // ─── Content: Pins ─────────────────────────────────────
  {
    name: "pin",
    category: "content",
    permission: "admin",
    description: "Pin a replied-to message.",
    usage: "/pin [loud]",
    examples: ["Reply: /pin", "Reply: /pin loud"],
    notes: ["Silent by default. Use 'loud' to notify members."],
    module: "pins",
  },
  {
    name: "permapin",
    category: "content",
    permission: "admin",
    description: "Send and pin a new message.",
    usage: "/permapin <text>",
    examples: ["/permapin Important announcement here"],
    module: "pins",
  },
  {
    name: "unpin",
    category: "content",
    permission: "admin",
    description: "Unpin the most recent pinned message.",
    usage: "/unpin",
    examples: ["/unpin"],
    module: "pins",
  },
  {
    name: "unpinall",
    category: "content",
    permission: "creator",
    description: "Unpin all messages in the chat.",
    usage: "/unpinall",
    examples: ["/unpinall"],
    notes: ["Creator only"],
    module: "pins",
  },
  {
    name: "antichannelpin",
    category: "content",
    permission: "admin",
    description: "Auto-unpin messages pinned by linked channels.",
    usage: "/antichannelpin <on|off>",
    examples: ["/antichannelpin on"],
    module: "pins",
  },
  {
    name: "cleanlinked",
    category: "content",
    permission: "admin",
    description: "Auto-delete messages from linked channels.",
    usage: "/cleanlinked <on|off>",
    examples: ["/cleanlinked on"],
    module: "pins",
  },

  // ─── Content: Echo ─────────────────────────────────────
  {
    name: "echo",
    category: "content",
    permission: "admin",
    description: "Send a message as the bot (supports HTML formatting).",
    usage: "/echo <text>",
    examples: ["/echo <b>Hello</b> everyone!"],
    notes: ["Deletes the command message"],
    module: "echo",
  },
  {
    name: "say",
    category: "content",
    permission: "admin",
    description: "Alias for /echo.",
    usage: "/say <text>",
    examples: ["/say Welcome to the group!"],
    module: "echo",
  },
  {
    name: "broadcast",
    category: "content",
    permission: "owner",
    description: "Broadcast a message to all chats (bot owner only).",
    usage: "/broadcast <text>",
    examples: ["/broadcast Bot update: new features available!"],
    notes: ["Bot owner only (BOT_OWNER_ID). Rate-limited."],
    module: "echo",
  },

  // ─── Content: Info ─────────────────────────────────────
  {
    name: "id",
    category: "content",
    permission: "everyone",
    description: "Get your user ID and/or the chat ID.",
    usage: "/id",
    examples: ["/id", "Reply: /id"],
    module: "info",
  },
  {
    name: "info",
    category: "content",
    permission: "everyone",
    description: "Get detailed user info.",
    longDescription:
      "Shows user ID, name, username, mention link, and group membership status. Targets replied-to user, @username, or user ID. Defaults to yourself.",
    usage: "/info [user]",
    examples: ["/info", "/info @username", "Reply: /info"],
    module: "info",
  },

  // ─── Settings: Log Channels ────────────────────────────
  {
    name: "setlog",
    category: "settings",
    permission: "admin",
    description: "Set a channel for action logging.",
    usage: "/setlog <channel>",
    examples: ["/setlog @mychannel", "/setlog -1001234567890"],
    notes: [
      "Add the bot to the channel first. You can also forward a message from the channel.",
    ],
    module: "log-channels",
  },
  {
    name: "unsetlog",
    category: "settings",
    permission: "admin",
    description: "Disable action logging.",
    usage: "/unsetlog",
    examples: ["/unsetlog"],
    module: "log-channels",
  },
  {
    name: "logchannel",
    category: "settings",
    permission: "admin",
    description: "Show the current log channel.",
    usage: "/logchannel",
    examples: ["/logchannel"],
    module: "log-channels",
  },
  {
    name: "logcategories",
    category: "settings",
    permission: "admin",
    description: "List all log categories with their status.",
    usage: "/logcategories",
    examples: ["/logcategories"],
    module: "log-channels",
  },
  {
    name: "log",
    category: "settings",
    permission: "admin",
    description: "Enable specific log categories.",
    usage: "/log <category> [category2]",
    examples: ["/log bans", "/log bans warns kicks"],
    module: "log-channels",
  },
  {
    name: "nolog",
    category: "settings",
    permission: "admin",
    description: "Disable specific log categories.",
    usage: "/nolog <category> [category2]",
    examples: ["/nolog joins", "/nolog joins leaves"],
    module: "log-channels",
  },

  // ─── Settings: Connections ─────────────────────────────
  {
    name: "connect",
    category: "settings",
    permission: "admin",
    description: "Connect to a group from PM for remote administration.",
    longDescription:
      "In a group, shows the chat ID to use for connecting. In PM, connects you to the specified group so you can run admin commands remotely.",
    usage: "/connect [chat_id]",
    examples: ["In group: /connect", "In PM: /connect -1001234567890"],
    module: "connections",
  },
  {
    name: "disconnect",
    category: "settings",
    permission: "everyone",
    description: "Disconnect from the currently connected group.",
    usage: "/disconnect",
    examples: ["/disconnect"],
    notes: ["PM only"],
    module: "connections",
  },
  {
    name: "connection",
    category: "settings",
    permission: "everyone",
    description: "Show the current active connection.",
    usage: "/connection",
    examples: ["/connection"],
    notes: ["PM only"],
    module: "connections",
  },
  {
    name: "reconnect",
    category: "settings",
    permission: "everyone",
    description: "Reconnect to the last used group.",
    usage: "/reconnect",
    examples: ["/reconnect"],
    notes: ["PM only"],
    module: "connections",
  },

  // ─── Settings: Cleaning ────────────────────────────────
  {
    name: "cleancommand",
    category: "settings",
    permission: "admin",
    description: "Enable auto-deletion of command messages by type.",
    usage: "/cleancommand <type>",
    examples: ["/cleancommand admin", "/cleancommand all"],
    notes: ["Use /cleancommandtypes to see available types"],
    module: "cleaning",
  },
  {
    name: "keepcommand",
    category: "settings",
    permission: "admin",
    description: "Disable auto-deletion for a command type.",
    usage: "/keepcommand <type>",
    examples: ["/keepcommand admin"],
    module: "cleaning",
  },
  {
    name: "cleancommandtypes",
    category: "settings",
    permission: "everyone",
    description: "List available command types for auto-deletion.",
    usage: "/cleancommandtypes",
    examples: ["/cleancommandtypes"],
    module: "cleaning",
  },
  {
    name: "cleanmsg",
    category: "settings",
    permission: "admin",
    description: "Enable auto-deletion of a message type.",
    usage: "/cleanmsg <type>",
    examples: ["/cleanmsg sticker", "/cleanmsg photo"],
    notes: ["Use /cleanmsgtypes to see available types"],
    module: "cleaning",
  },
  {
    name: "keepmsg",
    category: "settings",
    permission: "admin",
    description: "Disable auto-deletion for a message type.",
    usage: "/keepmsg <type>",
    examples: ["/keepmsg sticker"],
    module: "cleaning",
  },
  {
    name: "cleanmsgtypes",
    category: "settings",
    permission: "everyone",
    description: "List available message types for auto-deletion.",
    usage: "/cleanmsgtypes",
    examples: ["/cleanmsgtypes"],
    module: "cleaning",
  },
  {
    name: "cleanservice",
    category: "settings",
    permission: "admin",
    description: "Enable auto-deletion of service messages.",
    usage: "/cleanservice <type>",
    examples: ["/cleanservice join", "/cleanservice all"],
    notes: ["Types: join, leave, pin, photo, title, videochat, all"],
    module: "cleaning",
  },
  {
    name: "nocleanservice",
    category: "settings",
    permission: "admin",
    description: "Disable auto-deletion for a service message type.",
    usage: "/nocleanservice <type>",
    examples: ["/nocleanservice join"],
    module: "cleaning",
  },
  {
    name: "cleanservicetypes",
    category: "settings",
    permission: "everyone",
    description: "List available service message types for auto-deletion.",
    usage: "/cleanservicetypes",
    examples: ["/cleanservicetypes"],
    module: "cleaning",
  },

  // ─── Settings: Disabling ───────────────────────────────
  {
    name: "disabled",
    category: "settings",
    permission: "everyone",
    description: "List disabled commands in this group.",
    usage: "/disabled",
    examples: ["/disabled"],
    module: "disabling",
  },
  {
    name: "disableable",
    category: "settings",
    permission: "everyone",
    description: "List commands that can be disabled.",
    usage: "/disableable",
    examples: ["/disableable"],
    module: "disabling",
  },
  {
    name: "disable",
    category: "settings",
    permission: "admin",
    description: "Disable a command for non-admin users.",
    usage: "/disable <command>",
    examples: ["/disable rules", "/disable flood"],
    module: "disabling",
  },
  {
    name: "enable",
    category: "settings",
    permission: "admin",
    description: "Re-enable a disabled command.",
    usage: "/enable <command>",
    examples: ["/enable rules"],
    module: "disabling",
  },
  {
    name: "disabledel",
    category: "settings",
    permission: "admin",
    description: "Toggle auto-deletion of disabled command messages.",
    usage: "/disabledel <on|off>",
    examples: ["/disabledel on"],
    module: "disabling",
  },
  {
    name: "disableadmin",
    category: "settings",
    permission: "admin",
    description: "Toggle whether disabled commands apply to admins too.",
    usage: "/disableadmin <on|off>",
    examples: ["/disableadmin on"],
    module: "disabling",
  },

  // ─── Settings: Silent Actions ──────────────────────────
  {
    name: "silentactions",
    category: "settings",
    permission: "admin",
    description: "Toggle silent moderation actions (suppress bot responses).",
    usage: "/silentactions <on|off>",
    examples: ["/silentactions on"],
    module: "federations",
  },

  // ─── Federations ───────────────────────────────────────
  {
    name: "newfed",
    category: "federations",
    permission: "pm-only",
    description: "Create a new federation.",
    usage: "/newfed <name>",
    examples: ["/newfed Anti-Spam Network"],
    notes: ["PM only"],
    module: "federations",
  },
  {
    name: "renamefed",
    category: "federations",
    permission: "fed-owner",
    description: "Rename a federation.",
    usage: "/renamefed <fed_id> <new name>",
    examples: ["/renamefed abc123 My Updated Federation"],
    module: "federations",
  },
  {
    name: "delfed",
    category: "federations",
    permission: "fed-owner",
    description: "Delete a federation and unlink all chats.",
    usage: "/delfed <fed_id>",
    examples: ["/delfed abc123"],
    module: "federations",
  },
  {
    name: "fedinfo",
    category: "federations",
    permission: "everyone",
    description: "Show federation details.",
    usage: "/fedinfo [fed_id]",
    examples: ["/fedinfo", "/fedinfo abc123"],
    notes: ["Defaults to current chat's federation"],
    module: "federations",
  },
  {
    name: "fedadmins",
    category: "federations",
    permission: "everyone",
    description: "List federation admins.",
    usage: "/fedadmins [fed_id]",
    examples: ["/fedadmins"],
    module: "federations",
  },
  {
    name: "chatfed",
    category: "federations",
    permission: "everyone",
    description: "Show which federation this chat belongs to.",
    usage: "/chatfed",
    examples: ["/chatfed"],
    module: "federations",
  },
  {
    name: "myfeds",
    category: "federations",
    permission: "everyone",
    description: "List federations you own.",
    usage: "/myfeds",
    examples: ["/myfeds"],
    module: "federations",
  },
  {
    name: "fedpromote",
    category: "federations",
    permission: "fed-owner",
    description: "Promote a user to federation admin.",
    usage: "/fedpromote <user>",
    examples: ["/fedpromote @username"],
    module: "federations",
  },
  {
    name: "feddemote",
    category: "federations",
    permission: "fed-owner",
    description: "Demote a federation admin.",
    usage: "/feddemote <user>",
    examples: ["/feddemote @username"],
    module: "federations",
  },
  {
    name: "feddemoteme",
    category: "federations",
    permission: "everyone",
    description: "Self-demote from federation admin.",
    usage: "/feddemoteme",
    examples: ["/feddemoteme"],
    module: "federations",
  },
  {
    name: "fedreason",
    category: "federations",
    permission: "fed-owner",
    description: "Require a reason for federation bans.",
    usage: "/fedreason <on|off>",
    examples: ["/fedreason on"],
    module: "federations",
  },
  {
    name: "fednotif",
    category: "federations",
    permission: "fed-owner",
    description: "Toggle ban notifications in federation chats.",
    usage: "/fednotif <on|off>",
    examples: ["/fednotif on"],
    module: "federations",
  },
  {
    name: "setfedlog",
    category: "federations",
    permission: "fed-owner",
    description: "Set the current chat as the federation log channel.",
    usage: "/setfedlog",
    examples: ["/setfedlog"],
    module: "federations",
  },
  {
    name: "unsetfedlog",
    category: "federations",
    permission: "fed-owner",
    description: "Remove the federation log channel.",
    usage: "/unsetfedlog",
    examples: ["/unsetfedlog"],
    module: "federations",
  },
  {
    name: "fban",
    category: "federations",
    permission: "fed-admin",
    description: "Federation ban a user across all fed chats.",
    usage: "/fban <user> [reason]",
    examples: ["/fban @username spam across groups"],
    module: "federations",
  },
  {
    name: "unfban",
    category: "federations",
    permission: "fed-admin",
    description: "Remove a federation ban.",
    usage: "/unfban <user>",
    examples: ["/unfban @username"],
    module: "federations",
  },
  {
    name: "fbanlist",
    category: "federations",
    permission: "fed-admin",
    description: "List federation bans (up to 200).",
    usage: "/fbanlist [fed_id]",
    examples: ["/fbanlist"],
    module: "federations",
  },
  {
    name: "fedstat",
    category: "federations",
    permission: "everyone",
    description: "Check if a user is federation banned.",
    usage: "/fedstat [user]",
    examples: ["/fedstat", "/fedstat @username"],
    module: "federations",
  },
  {
    name: "fbanstat",
    category: "federations",
    permission: "everyone",
    description: "Alias for /fedstat.",
    usage: "/fbanstat [user]",
    examples: ["/fbanstat @username"],
    module: "federations",
  },
  {
    name: "subfed",
    category: "federations",
    permission: "fed-owner",
    description: "Subscribe to another federation's bans.",
    usage: "/subfed <fed_id>",
    examples: ["/subfed abc123"],
    module: "federations",
  },
  {
    name: "unsubfed",
    category: "federations",
    permission: "fed-owner",
    description: "Unsubscribe from a federation.",
    usage: "/unsubfed <fed_id>",
    examples: ["/unsubfed abc123"],
    module: "federations",
  },
  {
    name: "fedsubs",
    category: "federations",
    permission: "everyone",
    description: "List federation subscriptions.",
    usage: "/fedsubs",
    examples: ["/fedsubs"],
    module: "federations",
  },
  {
    name: "joinfed",
    category: "federations",
    permission: "creator",
    description: "Add this chat to a federation.",
    usage: "/joinfed <fed_id>",
    examples: ["/joinfed abc123"],
    notes: ["Group creator only"],
    module: "federations",
  },
  {
    name: "leavefed",
    category: "federations",
    permission: "creator",
    description: "Remove this chat from its federation.",
    usage: "/leavefed",
    examples: ["/leavefed"],
    notes: ["Group creator only"],
    module: "federations",
  },
  {
    name: "quietfed",
    category: "federations",
    permission: "admin",
    description: "Suppress federation ban notifications in this chat.",
    usage: "/quietfed <on|off>",
    examples: ["/quietfed on"],
    module: "federations",
  },
  {
    name: "importfbans",
    category: "federations",
    permission: "fed-owner",
    description: "Import federation bans from a JSON file.",
    longDescription:
      'Reply to a JSON file containing an array of objects with user_id and optional reason. Format: [{"user_id": 123, "reason": "spam"}]. Max 5MB / 10,000 entries.',
    usage: "/importfbans",
    examples: ["Reply to a JSON file: /importfbans"],
    notes: ["Max 5MB file size, 10,000 entries"],
    module: "federations",
  },

  // ─── Zenon: Wallet ─────────────────────────────────────
  {
    name: "zwallet",
    category: "zenon",
    permission: "everyone",
    description: "Link, view, verify, or unlink a Zenon wallet address.",
    longDescription:
      "With an address: links it to your Telegram account. No args: shows your linked address. 'verify': marks it as verified. 'unlink': removes the link.",
    usage: "/zwallet [address|verify|unlink]",
    examples: [
      "/zwallet z1qph8...",
      "/zwallet verify",
      "/zwallet unlink",
      "/zwallet",
    ],
    module: "zenon",
  },
  {
    name: "zbalance",
    category: "zenon",
    permission: "everyone",
    description: "Check ZNN/QSR token balances for an address.",
    usage: "/zbalance [address]",
    examples: ["/zbalance", "/zbalance z1qph8..."],
    notes: ["Uses your linked address if omitted"],
    module: "zenon",
  },
  {
    name: "zaddress",
    category: "zenon",
    permission: "everyone",
    description: "Show the bot's own Zenon wallet address.",
    usage: "/zaddress",
    examples: ["/zaddress"],
    notes: ["Requires bot wallet to be configured"],
    module: "zenon",
  },

  // ─── Zenon: Network ────────────────────────────────────
  {
    name: "zstats",
    category: "zenon",
    permission: "everyone",
    description: "Show Zenon network statistics.",
    usage: "/zstats",
    examples: ["/zstats"],
    notes: ["Shows sync state, height, peers, node version"],
    module: "zenon",
  },
  {
    name: "zmomentum",
    category: "zenon",
    permission: "everyone",
    description: "Show frontier momentum or a specific one by height.",
    usage: "/zmomentum [height]",
    examples: ["/zmomentum", "/zmomentum 123456"],
    module: "zenon",
  },

  // ─── Zenon: Tokens ─────────────────────────────────────
  {
    name: "ztoken",
    category: "zenon",
    permission: "everyone",
    description: "Get detailed info about a token by ZTS address.",
    usage: "/ztoken <zts_address>",
    examples: ["/ztoken zts1znnxxxxxxxxxxxxx9z4ulx"],
    notes: ["Shows name, symbol, supply, owner, mintable/burnable flags"],
    module: "zenon",
  },
  {
    name: "ztokens",
    category: "zenon",
    permission: "everyone",
    description: "List all tokens on the Zenon network.",
    usage: "/ztokens [page]",
    examples: ["/ztokens", "/ztokens 2"],
    module: "zenon",
  },

  // ─── Zenon: Pillars ────────────────────────────────────
  {
    name: "zpillar",
    category: "zenon",
    permission: "everyone",
    description: "Get info about a pillar by name.",
    usage: "/zpillar <name>",
    examples: ["/zpillar SultanOfStaking"],
    notes: ["Shows rank, weight, owner, reward percentages"],
    module: "zenon",
  },
  {
    name: "zpillars",
    category: "zenon",
    permission: "everyone",
    description: "List all pillars ranked by weight.",
    usage: "/zpillars [page]",
    examples: ["/zpillars", "/zpillars 3"],
    module: "zenon",
  },
  {
    name: "zdelegate",
    category: "zenon",
    permission: "everyone",
    description: "View delegation info or get delegation instructions.",
    usage: "/zdelegate [pillar_name]",
    examples: ["/zdelegate", "/zdelegate SultanOfStaking"],
    notes: ["No args shows your current delegation via linked address"],
    module: "zenon",
  },
  {
    name: "zrewards",
    category: "zenon",
    permission: "everyone",
    description: "Show uncollected staking and delegation rewards.",
    usage: "/zrewards [address]",
    examples: ["/zrewards", "/zrewards z1qph8..."],
    module: "zenon",
  },

  // ─── Zenon: Staking ────────────────────────────────────
  {
    name: "zstakes",
    category: "zenon",
    permission: "everyone",
    description: "Show staking entries with amounts and expiry times.",
    usage: "/zstakes [address]",
    examples: ["/zstakes", "/zstakes z1qph8..."],
    module: "zenon",
  },
  {
    name: "zstake",
    category: "zenon",
    permission: "everyone",
    description: "Show staking info and instructions.",
    usage: "/zstake",
    examples: ["/zstake"],
    module: "zenon",
  },
  {
    name: "zunstake",
    category: "zenon",
    permission: "everyone",
    description: "Show unstaking instructions.",
    usage: "/zunstake",
    examples: ["/zunstake"],
    module: "zenon",
  },

  // ─── Zenon: Plasma ─────────────────────────────────────
  {
    name: "zplasma",
    category: "zenon",
    permission: "everyone",
    description: "Show plasma info and QSR fusion entries.",
    usage: "/zplasma [address]",
    examples: ["/zplasma", "/zplasma z1qph8..."],
    module: "zenon",
  },
  {
    name: "zfuse",
    category: "zenon",
    permission: "bot-wallet",
    description: "Fuse QSR for plasma from the bot's wallet.",
    usage: "/zfuse <address> <amount>",
    examples: ["/zfuse z1qph8... 100"],
    notes: ["Requires bot wallet to be configured"],
    module: "zenon",
  },

  // ─── Zenon: Send ───────────────────────────────────────
  {
    name: "zsend",
    category: "zenon",
    permission: "bot-wallet",
    description: "Send tokens from the bot's wallet (with confirmation).",
    usage: "/zsend <address> <amount> [zts]",
    examples: ["/zsend z1qph8... 10", "/zsend z1qph8... 100 QSR"],
    notes: ["Shows inline confirm/cancel buttons. 60s timeout. Default token is ZNN."],
    module: "zenon",
  },

  // ─── Zenon: Bridge ─────────────────────────────────────
  {
    name: "zbridge",
    category: "zenon",
    permission: "everyone",
    description: "Show bridge info or list bridge networks.",
    usage: "/zbridge [networks]",
    examples: ["/zbridge", "/zbridge networks"],
    module: "zenon",
  },
  {
    name: "zwrap",
    category: "zenon",
    permission: "everyone",
    description: "Show wrapping instructions.",
    usage: "/zwrap",
    examples: ["/zwrap"],
    module: "zenon",
  },

  // ─── Zenon: HTLC ──────────────────────────────────────
  {
    name: "zhtlc",
    category: "zenon",
    permission: "everyone",
    description: "HTLC operations and info.",
    usage: "/zhtlc [help|info <id>|create|unlock]",
    examples: ["/zhtlc help", "/zhtlc info abc123..."],
    module: "zenon",
  },

  // ─── Zenon: Accelerator ────────────────────────────────
  {
    name: "zproposals",
    category: "zenon",
    permission: "everyone",
    description: "List Accelerator-Z funding proposals.",
    usage: "/zproposals [page]",
    examples: ["/zproposals", "/zproposals 2"],
    module: "zenon",
  },
  {
    name: "zproposal",
    category: "zenon",
    permission: "everyone",
    description: "Get details for a specific Accelerator-Z proposal.",
    usage: "/zproposal <project_id>",
    examples: ["/zproposal abc123..."],
    notes: ["Shows votes, funding, description"],
    module: "zenon",
  },
  {
    name: "zvote",
    category: "zenon",
    permission: "everyone",
    description: "Show Accelerator-Z voting info.",
    usage: "/zvote",
    examples: ["/zvote"],
    notes: ["Pillar holders only, via Syrius/CLI"],
    module: "zenon",
  },

  // ─── Zenon: Subscriptions ──────────────────────────────
  {
    name: "zsub",
    category: "zenon",
    permission: "admin",
    description: "Subscribe to Zenon network events.",
    usage: "/zsub <momentum|address> [z1_address]",
    examples: ["/zsub momentum", "/zsub address z1qph8..."],
    module: "zenon",
  },
  {
    name: "zunsub",
    category: "zenon",
    permission: "admin",
    description: "Unsubscribe from Zenon events or list subscriptions.",
    usage: "/zunsub [type|all|list]",
    examples: ["/zunsub list", "/zunsub all", "/zunsub momentum"],
    module: "zenon",
  },

  // ─── Zenon: Token Gating ───────────────────────────────
  {
    name: "zgate",
    category: "zenon",
    permission: "admin",
    description: "Configure token-gated group access.",
    longDescription:
      "Restrict group membership to users holding a minimum balance of a specific ZTS token. New joiners without a linked wallet or insufficient balance are kicked.",
    usage: "/zgate [info|enable <zts> <min>|disable|check]",
    examples: [
      "/zgate info",
      "/zgate enable zts1znnxxxxxxxxxxxxx9z4ulx 100",
      "/zgate disable",
      "/zgate check",
    ],
    notes: ["'check' lets users verify their own eligibility"],
    module: "zenon",
  },
];

/** Pre-built lookup map for O(1) command search */
const commandMap = new Map<string, CommandEntry>();
for (const entry of COMMAND_REGISTRY) {
  commandMap.set(entry.name, entry);
}

/** Look up a command by name */
export function getCommand(name: string): CommandEntry | undefined {
  return commandMap.get(name.toLowerCase().replace(/^\//, ""));
}

/** Get all commands in a category */
export function getCommandsByCategory(
  category: CommandCategory,
): CommandEntry[] {
  return COMMAND_REGISTRY.filter((c) => c.category === category);
}

/** Fuzzy search: prefix matches first, then description keyword matches */
export function searchCommands(query: string): CommandEntry[] {
  const q = query.toLowerCase().replace(/^\//, "");
  const prefixMatches = COMMAND_REGISTRY.filter((c) => c.name.startsWith(q));
  if (prefixMatches.length > 0) return prefixMatches.slice(0, 5);
  return COMMAND_REGISTRY.filter((c) =>
    c.description.toLowerCase().includes(q),
  ).slice(0, 5);
}

/** Format a permission level for display */
export function formatPermission(level: PermissionLevel): string {
  const labels: Record<PermissionLevel, string> = {
    everyone: "Everyone",
    admin: "Admin",
    creator: "Group Creator",
    owner: "Bot Owner",
    "pm-only": "PM Only",
    "fed-owner": "Federation Owner",
    "fed-admin": "Federation Admin",
    "bot-wallet": "Bot Wallet Required",
  };
  return labels[level];
}
